---
- name: Deploy Scientific Calculator with Docker
  hosts: server
  tasks:

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: amanve7/scientific-calculator:latest
        source: pull

    - name: Stop and remove existing container (if any)
      community.docker.docker_container:
        name: calculator-container
        state: absent

    - name: Run new container
      community.docker.docker_container:
        name: calculator-container
        image: amanve7/scientific-calculator:latest
        state: started
        restart_policy: always
        ports:
          - "8080:8080"  
